### ISSUE TITLE
Sev 3 - Sync in UAT

### ISSUE THREAD

**Issue by mraceati** [TashaundaATIV/Compass-Tracking#2]
From: Tashaunda Knighten On Behalf Of ATIV Support
Sent: Wednesday, December 16, 2015 4:32 PM
To: 'Woodfinn Support' support@woodfinn.zendesk.com
Cc: ATIV Support support@ativaluations.com
Subject: Sev 3 - Sync in UAT

The following orders are not showing in Port:
201512160019
SUN0211364 : 54 RAVEN GLASS LN, BLUFFTON, SC 29909
SUN0211365 : 54 RAVEN GLASS LN, BLUFFTON, SC 29909
201512160026
SUN0211378 : 4709 S ATLANTIC AVE, SMYRNA BEACH, FL 32169
SUN0211379 : 4709 S ATLANTIC AVE, SMYRNA BEACH, FL 32169Please sync

**Comment by mraceati** [comment]
Ticket #4394: Sev 3 - Sync in UAT 
Your request (#4394) has been updated. 
To review the status of the request and add additional comments, follow the link below:
http://support.woodfinn.com/requests/4394
You can also add a comment by replying to this email.

Daniel Servin (Woodfinn Support) 
Dec 16, 15:34 
Hello Tashaunda,
Thank for contacting our Woodfinn Support Team.
My name is Daniel Servin and I will take ownership of your case.
At this moment, Dev team is currently making some test in UAT that is causing this mismatches
this will soon end and orders will be ok.
Let me know if more help or info is needed
Thanks
Daniel Servin
Support Team (C)

**Comment by mraceati** [comment]
From: Miguel Race On Behalf Of ATIV Support
Sent: Wednesday, December 16, 2015 4:59 PM
To: 'Woodfinn Support' <support+id4394@woodfinn.zendesk.com>; ATIV Support support@ativaluations.com
Cc: 'Daniel Servin' dservin@woodfinn.com; Tashaunda Knighten tknighten@ativaluations.com
Subject: RE: [Woodfinn Support] Re: Sev 3 - Sync in UAT
Importance: High

Daniel this is urgently needed for testing.  Please expedite

**Comment by TashaundaATIV** [comment]
Daniel Servin (Woodfinn Support) 
Dec 16, 16:06 
Hello Mike,
Dev Team just notified me that the test in UAT are done.
you should see sync will take place soon.
Let me know if more help is needed
Thanks
Daniel Servin
Support Team (C)

**Comment by TashaundaATIV** [comment]
[‎12/‎16/‎2015 4:45 PM] Tricia Peter: 
it looks like they've synced the orders now as I received the emails about being assigned orders and the orders are now showing on appraiser port
