### ISSUE TITLE
Sev 3 - Registration letter not going out - McGuire

### ISSUE THREAD

**Issue by mraceati** [TashaundaATIV/Compass-Tracking#3]
McGuire — Amanda Bartlett 

@Escalate- IT Good Afternoon - The registration letter for this appraiser is not going out. Please try to expedite this, we have 2 rush orders to assign to him. Thanks! 

 View/Comment 
  or reply to this email

**Comment by mraceati** [comment]
From: Miguel Race On Behalf Of ATIV Support
Sent: Wednesday, December 16, 2015 4:38 PM
To: 'Reply to Chatter' 1ll2gbehlkrar23p.hb29drmzdim3yfdx.iqiomiagfvofsatd@ep09f5sbnqv5h6ds.2z0bjnxyepv4pw.i-igl5eac.na15.chatter.salesforce.com; ATIV Support support@ativaluations.com
Subject: RE: Amanda Bartlett mentioned you in a post

Contacting Wf to resolve

**Comment by mraceati** [comment]
Ticket #4395: Sev 3 - Registration letter not going out - McGuire 
Thank you for contacting Woodfinn Support. Your support ticket was successfully submitted.
A support professional will contact you to begin the troubleshooting and resolution of your request.
For all updates to this ticket, please ensure that the ticket number (#4395) is included in the subject line.
You can review the status of your ticket and add additional comments any time by following this link:
http://support.woodfinn.com/requests/4395
We will get back to you shortly,
The Woodfinn Support Team
Here is a summary of your request:

ATIV Support 
Dec 16, 15:41 
Good Afternoon,
The registration letter for this vendor is not going out. Please have this corrected and addressed asap
McGuire, Robert
https://na15.salesforce.com/a0Ni000001ZxUEG
Thank you.
Miguel (Mike) Race
Business Analyst
Phone: 508.655.0342 x 1025
Cell: 321-604-9879
ATI Valuations
It’s the I.M.P.A.C.T (http://www.americantitleinc.com/ati/About-Us/Core-Values) . on our customers that matters most to us at American Title, Inc. Tell us about our I.M.P.A.C.T (http://www.americantitleinc.com/ati/About-Us/Core-Values) . on you! Contact our owners with compliments or opportunities for improvement at Mackintosh@americantitleinc.com or 402-778.4321.
From: Amanda Bartlett in Chatter [mailto:reply@chatter.salesforce.com]
Sent: Wednesday, December 16, 2015 4:36 PM
To: ATIV Support support@ativaluations.com
Subject: Amanda Bartlett mentioned you in a post
@Escalate- IT Good Afternoon - The registration letter for this appraiser is not going out. Please try to expedite this, we have 2 rush orders to assign to him. Thanks! 
McGuire (https://na15.salesforce.com/a0Ni000001ZxUEG?fromEmail=1&s1oid=00Di0000000Igl5&s1nid=000000000000000&s1uid=005i0000003pwoL&s1ext=0&emkind=chatterPostNotification&emtm=1450301745623) — Amanda Bartlett (https://na15.salesforce.com/005i0000003ppNI?fromEmail=1&s1oid=00Di0000000Igl5&s1nid=000000000000000&s1uid=005i0000003pwoL&s1ext=0&emkind=chatterPostNotification&emtm=1450301745623)
@Escalate- IT (https://na15.salesforce.com/005i0000003pwoL?fromEmail=1&s1oid=00Di0000000Igl5&s1nid=000000000000000&s1uid=005i0000003pwoL&s1ext=0&emkind=chatterPostNotification&emtm=1450301745623) Good Afternoon - The registration letter for this appraiser is not going out. Please try to expedite this, we have 2 rush orders to assign to him. Thanks! 
View/Comment (https://na15.salesforce.com/0D5i0000037JPcU?fromEmail=1&s1oid=00Di0000000Igl5&s1nid=000000000000000&s1uid=005i0000003pwoL&s1ext=0&emkind=chatterPostNotification&emtm=1450301745623&OpenCommentForEdit=1)
or reply to this email
You're receiving emails when someone "Mentions me in a post."
To change or turn off Chatter email, log in (https://na15.salesforce.com/_ui/core/feeds/notification/ChatterEmailSettings?setupid=CollaborationEmailSettings&fromEmail=1&s1oid=00Di0000000Igl5&s1nid=000000000000000&s1uid=005i0000003pwoL&s1ext=0&emkind=chatterPostNotification&emtm=1450301745623) as support@ativaluations.com.
salesforce.com, inc. The Landmark @ One Market, Suite 300 San Francisco, CA 94105
This message may contain confidential and/or privileged information. If you are not the addressee or authorized to receive this for the addressee, you must not use, copy, disclose, or take any action based on this message or any information herein. If you have received this message in error, please advise the sender immediately by reply e-mail and delete this message. Thank you for your cooperation.
Attachment(s)
image001.png

**Comment by TashaundaATIV** [comment]
Daniel Servin (Woodfinn Support) 
Dec 16, 16:39 
Hello Mike,
I have manually registered Vendor
please let me know if more help is needed.
Thanks
Daniel Servin
Support Team (C)

**Comment by TashaundaATIV** [comment]
Noted the vendor has been manually registered in Chatter.
